%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-seed-r7-navigation
Version:        0.3.3
Release:        1%{?dist}
Summary:        ROS seed_r7_navigation package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-amcl
Requires:       ros-melodic-gmapping
Requires:       ros-melodic-joy
Requires:       ros-melodic-map-server
Requires:       ros-melodic-move-base
Requires:       ros-melodic-move-base-msgs
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-rospy
Requires:       ros-melodic-teb-local-planner
Requires:       ros-melodic-teleop-twist-joy
Requires:       ros-melodic-urg-node
BuildRequires:  ros-melodic-amcl
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-gmapping
BuildRequires:  ros-melodic-joy
BuildRequires:  ros-melodic-map-server
BuildRequires:  ros-melodic-move-base
BuildRequires:  ros-melodic-move-base-msgs
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-rospy
BuildRequires:  ros-melodic-teb-local-planner
BuildRequires:  ros-melodic-teleop-twist-joy
BuildRequires:  ros-melodic-urg-node

%description
The seed_r7_navigation package

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Wed Dec 04 2019 hi.kondo <hi.kondo@thk.co.jp> - 0.3.3-1
- Autogenerated by Bloom

